### PR TITLE
Finish renaming Trino

### PR DESCRIPTION
**Pull request by nineinchnick**
Finish renaming Trino by removing TODOs remaining in tests.

### CODE REVIEW

**Comment by nineinchnick** [comment]
I don't know why CI failed. It's also failing in the same way when I run it in a Linux VM with jdk8 but works on Windows when executed from IntelliJ. I had to create a `settings.xml` file and I used this:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
<localRepository/>
<interactiveMode/>
<offline/>
<pluginGroups/>
<servers/>
<mirrors/>
<proxies/>
<profiles/>
<activeProfiles/>
</settings>
```

**Comment by electrum** [comment]
This took me a while to figure out. The compiler fails with a confusing
```
[ERROR] invalid-skipped/src/main/java/its/InvalidPlugin.java:[3,19] error: cannot access Plugin
```
The problem is that Trino requires JDK 11 but we were compiling and running under JDK 8.

**Comment by electrum** [comment]
I'll put up a new PR to fix it. This turns out to be non-trivial (and subtle) to fix.

**Comment by electrum** [comment]
Replaced by #13

**Pull request closed without merging**
