### PR TITLE
Update plugin

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* use latest Takari parent POM, update takari test tooling
* compile against latest Maven (to pick up deprecations), keep prerequisite
* update tooling
* update p-u to latest Maven 3.x (keep in [3,4) range)
* aling maven core and maven artifact, make it provided as it is
* mark mojos thread safe (as they seems as they are, please tell if I missed something)
* update lifecycle, do NOT use Maven2 plugin ever ever again
* use wrapper and do not rely on 3rd party provided Maven: this way you are fully in control

### CODE REVIEW

**Comment by wendigo** [comment]
@cstamas please update first commit message. I'll merge this PR after that.

**Review by wendigo — APPROVED** [review]

**Comment by cstamas** [comment]
squashed and message updated

**Comment by cstamas** [comment]
A release would be welcome as well...

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
Tested locally. Seems good to go.

**Pull request merged**
